NAME _PROGRAM ; 
BODY DATA INTEGER16 _AAAAAAA, _BBBBBBB ;
  GET ( _AAAAAAA )
  GET ( _BBBBBBB )
  WHILE  _AAAAAAA >= 1 
    _AAAAAAA << _AAAAAAA - 1
	IF (_AAAAAAA <= _BBBBBBB) EXIT WHILE;
    PUT ( _AAAAAAA )
  END WHILE
END
