NAME _PROGRAM ; 
BODY DATA INTEGER16 _VALUEIN, _VALUMOD, _IIINDEX;
  GET (_VALUEIN)
  2 >> _IIINDEX
  WHILE _IIINDEX * _IIINDEX <= _VALUEIN
    FOR _VALUEIN MOD _IIINDEX >> _VALUMOD TO 0 DO
      PUT (_IIINDEX)
      _VALUEIN DIV _IIINDEX >> _VALUEIN
      _VALUEIN MOD _IIINDEX - 1 >> _VALUMOD
    ;
   _IIINDEX + 1 >> _IIINDEX
  END WHILE
  IF (_VALUEIN >= 2) PUT (_VALUEIN);
END