NAME _PROGRAM ; 
BODY DATA INTEGER16 _VALUEIN, _VALUMOD, _IIINDEX;
  GET (_VALUEIN)
  _IIINDEX << 2
  WHILE _IIINDEX * _IIINDEX <= _VALUEIN
    FOR _VALUMOD << _VALUEIN MOD _IIINDEX TO 0 DO
      PUT (_IIINDEX)
      _VALUEIN << _VALUEIN DIV _IIINDEX
      _VALUMOD << _VALUEIN MOD _IIINDEX - 1
    ;
  _IIINDEX << _IIINDEX + 1
  END WHILE
  IF (_VALUEIN >= 2) PUT (_VALUEIN);
END
