NAME _PROGRAM ; 
BODY DATA INTEGER16 _VALUEIN , _DEVIDER , _REMAIND , _CYCLEAC , _CYCLEBC , _CYCLECC ;
  GET ( _VALUEIN )
  _VALUEIN << _VALUEIN + 1
  FOR  _CYCLEAC << 0 TO 32767 DO
    _DEVIDER << _VALUEIN - 1
    FOR  _CYCLEBC << 0 TO 32767 DO 
      IF ( _DEVIDER >= 2 ) ; ELSE GOTO _ENDCYCB ;
      _REMAIND << _VALUEIN
      FOR  _CYCLECC << 0 TO 32767 DO
        IF ( _REMAIND >= _DEVIDER ) ; ELSE GOTO _ENDCYCC ;
        _REMAIND << _REMAIND - _DEVIDER
      ;
      _ENDCYCC :
      IF ( _REMAIND == 0 ) GOTO _ENDCYCB ;
      _DEVIDER << _DEVIDER - 1
    ;
    _ENDCYCB :
    IF ( _DEVIDER == 1 ) GOTO _ENDCYCA ;
    _VALUEIN << _VALUEIN + 1
  ;
  _ENDCYCA :
  PUT ( _VALUEIN )
END
